sonar.projectKey=aceest-fitness-gym
sonar.projectName=ACEest Fitness & Gym
sonar.projectVersion=2.0

sonar.sources=aceest_app,app.py
sonar.tests=tests
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/__pycache__/**,**/*.db,**/*.pdf,venv/**,.venv/**
sonar.test.inclusions=tests/**/*.py
